
- name: Deploy Alertmanager
  hosts: monitoring-servers
  become: true
  
  vars_files:
    - "../../vars/global.yml"
    - "../../secrets/vault_secrets.yaml"
    - "../../secrets/alert_secrets.yml"

  roles:
    - role: deploy-alertmanager