---
- name: Deploy Portainer Agent
  hosts: portainer-hosts
  become: true
  
  vars_files:
    - "../../vars/global.yml"
    - "../../secrets/vault_secrets.yaml"

  roles:
    - role: deploy-portainer-agent