---
- name: Deploy MySQL on srv2
  hosts: db-hosts
  become: true
  gather_facts: false

  vars_files:
    - "../../secrets/vault_secrets.yaml"
    - "../../secrets/db_secrets.yaml"
    - "../../vars/global.yml"

  roles:
    - role: deploy-mysql
