[servers]
team2.srv1 ansible_host=srv1_ansible ansible_port=22 server_hostname="srv1"
team2.srv2 ansible_host=srv2_ansible ansible_port=22 server_hostname="srv2"
#team2.srv1 ansible_host=10.145.141.162 ansible_port=22 server_hostname="srv2"

#srv1
[dbeaver-servers]
team2.srv1
[elgg-servers]
team2.srv1
[proxy-servers]
team2.srv1
[portainer-servers] 
team2.srv1

#srv2
[db-hosts]
team2.srv2
[portainer-hosts]
team2.srv2
[monitoring-servers]
team2.srv2

[all:vars]
ansible_python_interpreter=/usr/bin/python3