docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

# Репозиторий Docker
docker_repo_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
docker_repo_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

# Пакеты Docker
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin