- name: Ensure Python 3 and pip are installed
  become: true
  ansible.builtin.package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install PyMySQL from system package
  become: true
  ansible.builtin.apt:
    name: python3-pymysql
    state: present
    update_cache: yes
    
- name: Ensure base and data directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ db_project_path }}"
    - "{{ db_data_path }}"


- name: Ensure Docker network for services exists
  community.docker.docker_network:
    name: "{{ db_network }}"
    state: present