- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ db_project_path }}/docker-compose.yml"
    mode: '0644'

- name: Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ db_project_path }}"
    state: present