- name: Include preparation tasks
  include_tasks: 01_prepare.yaml

- name: Include container deployment tasks
  include_tasks: 02_deploy.yaml

- name: Include database configuration tasks
  include_tasks: 03_configure.yaml