- name: My first play
  hosts: servers

  # vars_files:
  #   - "../secrets/vault_secrets.yaml"
  
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world