---
# Основные настройки
portainer_image: "portainer/portainer-ce:latest"
portainer_container_name: "portainer.team2.lab"
portainer_restart_policy: "unless-stopped"

# Сеть
portainer_network: "{{ global_docker_network }}"

portainer_project_dir: "{{ base_services_dir }}/portainer"
portainer_data_dir: "{{ portainer_project_dir }}/data"

# Настройки Portainer
# Если true, порт 9000 будет проброшен наружу
portainer_publish_port: false
portainer_host_port: "8081"

# Базовый URL (для работы за прокси)
portainer_base_url: "/portainer"