---
- name: Ensure Docker network exists
  community.docker.docker_network:
    name: "{{ proxy_network }}"
    state: present

- name: Create Nginx directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ proxy_project_dir }}"
    - "{{ proxy_config_dir }}"
    - "{{ proxy_certs_dir }}"
    - "{{ proxy_logs_dir }}"

- name: Ensure OpenSSL is installed
  package:
    name: openssl
    state: present

- name: Generate Self-Signed SSL Certificate
  shell: >
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout {{ proxy_certs_dir }}/{{ ssl_key_file }}
    -out {{ proxy_certs_dir }}/{{ ssl_cert_file }}
    -subj "/C=US/ST=State/L=City/O=Team2/CN=localhost"
  args:
    creates: "{{ proxy_certs_dir }}/{{ ssl_cert_file }}" # Не пересоздавать, если файл уже есть

- name: Set permissions for private key
  file:
    path: "{{ proxy_certs_dir }}/{{ ssl_key_file }}"
    mode: '0600' # Ключ должен быть доступен только владельцу

- name: Copy Nginx configuration
  template:
    src: nginx.conf.j2
    dest: "{{ proxy_config_dir }}/default.conf"
    mode: '0644'

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ proxy_project_dir }}/docker-compose.yml"
    mode: '0644'

- name: Deploy Nginx Reverse Proxy
  community.docker.docker_compose_v2:
    project_src: "{{ proxy_project_dir }}"
    state: present
    pull: always