name: Deploy infrastructure with Ansible

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

env:
  ANSIBLE_CONFIG: ansible/ansible.cfg

jobs:

  delivery:
    name: Delivery secrets files
    runs-on: self-hosted
    steps: 

      - name: Prepare vault password file
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: |
          echo "$VAULT_PASS" > ansible/.vault_pass.txt

      - name: Create vault files from GitHub Secrets
        env:
          VAULT_SECRETS_CONTENT: ${{ secrets.VAULT_SECRETS }}
          USERS_DATA_CONTENT: ${{ secrets.VAULT_USERS_DATA }}
          DB_SECRETS_CONTENT: ${{ secrets.DB_SECRETS }}
        run: |
          cd ansible
          mkdir -p secrets
          
          echo "$VAULT_SECRETS_CONTENT" > secrets/vault_secrets.yaml
          echo "$USERS_DATA_CONTENT" > secrets/vault_users.yaml
          echo "$DB_SECRETS_CONTENT" > secrets/db_secrets.yaml
          
          ansible-vault encrypt secrets/vault_secrets.yaml
          ansible-vault encrypt secrets/vault_users.yaml
          ansible-vault encrypt secrets/db_secrets.yaml

      - name: Cleanup vault pass file
        run: rm -f ansible/.vault_pass.txt

  validate:
    name: Lint and Validate Ansible
    runs-on: self-hosted
    needs: delivery 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare vault password file
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: |
          echo "$VAULT_PASS" > ansible/.vault_pass.txt

      - name: Debug working directory
        run: |
          pwd && ls -la
          cd ansible
          ls -la

      - name: Validate syntax
        run: |
          cd ansible
          ansible-lint playbooks || echo "Lint warnings only"

      - name: Test inventory
        run: |
          cd ansible
          ansible-playbook ./playbooks/ping-host.yml

      - name: Cleanup vault pass file
        run: rm -f ansible/.vault_pass.txt
  
  deploy:
    name: Run Ansible deployment
    runs-on: self-hosted  
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare vault password file
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
        run: |
          echo "$VAULT_PASS" > ansible/.vault_pass.txt

      - name: Run Ansible playbooks
        run: |
          cd ansible
          # Разворачиваем базовую систему
          ansible-playbook playbooks/server-configurations/base-setup.yml
          # Управляем пользователями
          ansible-playbook playbooks/server-configurations/user-management.yml
          # Настраиваем Docker
          ansible-playbook playbooks/server-configurations/docker-setup.yml
          # Устанавливаем и настраиваем базу данных
          ansible-playbook playbooks/services/deploy-mysql.yml
          # Устанавливаем и настраиваем Elgg
          ansible-playbook playbooks/services/deploy-elgg.yml

      - name: Cleanup vault pass file
        run: rm -f ansible/.vault_pass.txt
