name: Deploy infrastructure with Ansible

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  delivery:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Prepare vault password file
        run: echo "${{ secrets.VAULT_PASS }}" > ansible/.vault_pass.txt

      - name: Create vault files
        run: |
          cd ansible
          mkdir -p secrets
          echo "${{ secrets.VAULT_SECRETS }}" > secrets/vault_secrets.yaml
          echo "${{ secrets.VAULT_USERS_DATA }}" > secrets/vault_users.yaml
          echo "${{ secrets.DB_SECRETS }}" > secrets/db_secrets.yaml
          ansible-vault encrypt secrets/vault_secrets.yaml
          ansible-vault encrypt secrets/vault_users.yaml
          ansible-vault encrypt secrets/db_secrets.yaml

      - run: rm -f ansible/.vault_pass.txt

      - name: Upload encrypted vault files
        uses: actions/upload-artifact@v4
        with:
          name: vaults
          path: ansible/secrets/*


  validate:
    runs-on: self-hosted
    needs: delivery

  

    steps:
    
      - uses: actions/checkout@v4

      - name: Download vaults
        uses: actions/download-artifact@v4
        with:
          name: vaults
          path: ansible/secrets

      - name: Download vaults
        uses: actions/download-artifact@v4
        with:
          name: vaults
          path: ansible/secrets

      - name: Prepare vault pass
        run: echo "${{ secrets.VAULT_PASS }}" > ansible/.vault_pass.txt

      - name: Test inventory
        run: |
          cd ansible
          ansible-playbook playbooks/ping-host.yml
          ansible all -m ping -vvv

      - run: rm -f ansible/.vault_pass.txt


  deploy:
    runs-on: self-hosted
    needs: validate

    steps:
      - uses: actions/checkout@v4

      - name: Prepare vault pass
        run: echo "${{ secrets.VAULT_PASS }}" > ansible/.vault_pass.txt

      - name: Run playbooks
        run: |
          cd ansible
          ansible-playbook playbooks/server-configurations/base-setup.yml
          ansible-playbook playbooks/server-configurations/user-management.yml
          ansible-playbook playbooks/server-configurations/docker-setup.yml
          ansible-playbook playbooks/services/deploy-mysql.yml
          ansible-playbook playbooks/services/deploy-elgg.yml

      - run: rm -f ansible/.vault_pass.txt
